const express=require('express');
const router=express.Router();
const user_controller=require('../controllers/user_controller');
router.get('/home',user_controller.displayHomeSpecific);
router.get('/home/underconstruction',user_controller.displayUC);
router.get('/home/logout',user_controller.endSession);
router.get('/home/deleteaccount',user_controller.deleteUser);
router.get('/home/transactions',user_controller.displaySpecificTransactions);
router.post('/home/addgold',user_controller.addGold);
router.post('/home/transact',user_controller.makeTransaction);
router.get('/review',user_controller.review);
router.post('/review/create',user_controller.createReview);
module.exports=router;